hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
reorder_imports = true
newline_style = "Unix"
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
